spring:
  application:
    name: service-provider
eureka:
  instance:
    hostname: localhost
    metadata-map:
      asMap: abc
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${random.int}
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    instance-info-replication-interval-seconds: 10
server:
  port: 0
