spring:
  profiles: provider1
  application:
    name: service-provider
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
server:
  port: 8080

---

spring:
  profiles: provider2
  application:
    name: service-provider
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
server:
  port: 8081