server:
  port: 9000
spring:
  application:
    name: service-invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/