server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false # 关闭自我保护
  instance:
    hostname: eureka1
    metadata-map:
          asMap: egf1
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
spring:
  profiles:  eureka1
  application:
    name: eureka-server

---

server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
    metadata-map:
      asMap: egf2
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
spring:
  profiles:  eureka2
  application:
    name: eureka-server

---

server:
  port: 8763
eureka:
  instance:
    hostname: eureka3
    metadata-map:
     asMap: egf3
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
spring:
  profiles:  eureka3
  application:
    name: eureka-server